/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	context "context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	resourcev1beta1 "sigs.k8s.io/dra-driver-nvidia-gpu/api/nvidia.com/resource/v1beta1"
	scheme "sigs.k8s.io/dra-driver-nvidia-gpu/pkg/nvidia.com/clientset/versioned/scheme"
)

// ComputeDomainCliquesGetter has a method to return a ComputeDomainCliqueInterface.
// A group's client should implement this interface.
type ComputeDomainCliquesGetter interface {
	ComputeDomainCliques(namespace string) ComputeDomainCliqueInterface
}

// ComputeDomainCliqueInterface has methods to work with ComputeDomainClique resources.
type ComputeDomainCliqueInterface interface {
	Create(ctx context.Context, computeDomainClique *resourcev1beta1.ComputeDomainClique, opts v1.CreateOptions) (*resourcev1beta1.ComputeDomainClique, error)
	Update(ctx context.Context, computeDomainClique *resourcev1beta1.ComputeDomainClique, opts v1.UpdateOptions) (*resourcev1beta1.ComputeDomainClique, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*resourcev1beta1.ComputeDomainClique, error)
	List(ctx context.Context, opts v1.ListOptions) (*resourcev1beta1.ComputeDomainCliqueList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *resourcev1beta1.ComputeDomainClique, err error)
	ComputeDomainCliqueExpansion
}

// computeDomainCliques implements ComputeDomainCliqueInterface
type computeDomainCliques struct {
	*gentype.ClientWithList[*resourcev1beta1.ComputeDomainClique, *resourcev1beta1.ComputeDomainCliqueList]
}

// newComputeDomainCliques returns a ComputeDomainCliques
func newComputeDomainCliques(c *ResourceV1beta1Client, namespace string) *computeDomainCliques {
	return &computeDomainCliques{
		gentype.NewClientWithList[*resourcev1beta1.ComputeDomainClique, *resourcev1beta1.ComputeDomainCliqueList](
			"computedomaincliques",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *resourcev1beta1.ComputeDomainClique { return &resourcev1beta1.ComputeDomainClique{} },
			func() *resourcev1beta1.ComputeDomainCliqueList { return &resourcev1beta1.ComputeDomainCliqueList{} },
		),
	}
}
