/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	context "context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	resourcev1beta1 "sigs.k8s.io/dra-driver-nvidia-gpu/api/nvidia.com/resource/v1beta1"
	scheme "sigs.k8s.io/dra-driver-nvidia-gpu/pkg/nvidia.com/clientset/versioned/scheme"
)

// KVCachePoolsGetter has a method to return a KVCachePoolInterface.
// A group's client should implement this interface.
type KVCachePoolsGetter interface {
	KVCachePools() KVCachePoolInterface
}

// KVCachePoolInterface has methods to work with KVCachePool resources.
type KVCachePoolInterface interface {
	Create(ctx context.Context, kVCachePool *resourcev1beta1.KVCachePool, opts v1.CreateOptions) (*resourcev1beta1.KVCachePool, error)
	Update(ctx context.Context, kVCachePool *resourcev1beta1.KVCachePool, opts v1.UpdateOptions) (*resourcev1beta1.KVCachePool, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, kVCachePool *resourcev1beta1.KVCachePool, opts v1.UpdateOptions) (*resourcev1beta1.KVCachePool, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*resourcev1beta1.KVCachePool, error)
	List(ctx context.Context, opts v1.ListOptions) (*resourcev1beta1.KVCachePoolList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *resourcev1beta1.KVCachePool, err error)
	KVCachePoolExpansion
}

// kVCachePools implements KVCachePoolInterface
type kVCachePools struct {
	*gentype.ClientWithList[*resourcev1beta1.KVCachePool, *resourcev1beta1.KVCachePoolList]
}

// newKVCachePools returns a KVCachePools
func newKVCachePools(c *ResourceV1beta1Client) *kVCachePools {
	return &kVCachePools{
		gentype.NewClientWithList[*resourcev1beta1.KVCachePool, *resourcev1beta1.KVCachePoolList](
			"kvcachepools",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *resourcev1beta1.KVCachePool { return &resourcev1beta1.KVCachePool{} },
			func() *resourcev1beta1.KVCachePoolList { return &resourcev1beta1.KVCachePoolList{} },
		),
	}
}
