/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

import (
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
	resourcev1beta1 "sigs.k8s.io/dra-driver-nvidia-gpu/api/nvidia.com/resource/v1beta1"
)

// ComputeDomainLister helps list ComputeDomains.
// All objects returned here must be treated as read-only.
type ComputeDomainLister interface {
	// List lists all ComputeDomains in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*resourcev1beta1.ComputeDomain, err error)
	// ComputeDomains returns an object that can list and get ComputeDomains.
	ComputeDomains(namespace string) ComputeDomainNamespaceLister
	ComputeDomainListerExpansion
}

// computeDomainLister implements the ComputeDomainLister interface.
type computeDomainLister struct {
	listers.ResourceIndexer[*resourcev1beta1.ComputeDomain]
}

// NewComputeDomainLister returns a new ComputeDomainLister.
func NewComputeDomainLister(indexer cache.Indexer) ComputeDomainLister {
	return &computeDomainLister{listers.New[*resourcev1beta1.ComputeDomain](indexer, resourcev1beta1.Resource("computedomain"))}
}

// ComputeDomains returns an object that can list and get ComputeDomains.
func (s *computeDomainLister) ComputeDomains(namespace string) ComputeDomainNamespaceLister {
	return computeDomainNamespaceLister{listers.NewNamespaced[*resourcev1beta1.ComputeDomain](s.ResourceIndexer, namespace)}
}

// ComputeDomainNamespaceLister helps list and get ComputeDomains.
// All objects returned here must be treated as read-only.
type ComputeDomainNamespaceLister interface {
	// List lists all ComputeDomains in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*resourcev1beta1.ComputeDomain, err error)
	// Get retrieves the ComputeDomain from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*resourcev1beta1.ComputeDomain, error)
	ComputeDomainNamespaceListerExpansion
}

// computeDomainNamespaceLister implements the ComputeDomainNamespaceLister
// interface.
type computeDomainNamespaceLister struct {
	listers.ResourceIndexer[*resourcev1beta1.ComputeDomain]
}
