/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

import (
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
	resourcev1beta1 "sigs.k8s.io/dra-driver-nvidia-gpu/api/nvidia.com/resource/v1beta1"
)

// ComputeDomainCliqueLister helps list ComputeDomainCliques.
// All objects returned here must be treated as read-only.
type ComputeDomainCliqueLister interface {
	// List lists all ComputeDomainCliques in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*resourcev1beta1.ComputeDomainClique, err error)
	// ComputeDomainCliques returns an object that can list and get ComputeDomainCliques.
	ComputeDomainCliques(namespace string) ComputeDomainCliqueNamespaceLister
	ComputeDomainCliqueListerExpansion
}

// computeDomainCliqueLister implements the ComputeDomainCliqueLister interface.
type computeDomainCliqueLister struct {
	listers.ResourceIndexer[*resourcev1beta1.ComputeDomainClique]
}

// NewComputeDomainCliqueLister returns a new ComputeDomainCliqueLister.
func NewComputeDomainCliqueLister(indexer cache.Indexer) ComputeDomainCliqueLister {
	return &computeDomainCliqueLister{listers.New[*resourcev1beta1.ComputeDomainClique](indexer, resourcev1beta1.Resource("computedomainclique"))}
}

// ComputeDomainCliques returns an object that can list and get ComputeDomainCliques.
func (s *computeDomainCliqueLister) ComputeDomainCliques(namespace string) ComputeDomainCliqueNamespaceLister {
	return computeDomainCliqueNamespaceLister{listers.NewNamespaced[*resourcev1beta1.ComputeDomainClique](s.ResourceIndexer, namespace)}
}

// ComputeDomainCliqueNamespaceLister helps list and get ComputeDomainCliques.
// All objects returned here must be treated as read-only.
type ComputeDomainCliqueNamespaceLister interface {
	// List lists all ComputeDomainCliques in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*resourcev1beta1.ComputeDomainClique, err error)
	// Get retrieves the ComputeDomainClique from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*resourcev1beta1.ComputeDomainClique, error)
	ComputeDomainCliqueNamespaceListerExpansion
}

// computeDomainCliqueNamespaceLister implements the ComputeDomainCliqueNamespaceLister
// interface.
type computeDomainCliqueNamespaceLister struct {
	listers.ResourceIndexer[*resourcev1beta1.ComputeDomainClique]
}
