/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

import (
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
	resourcev1beta1 "sigs.k8s.io/dra-driver-nvidia-gpu/api/nvidia.com/resource/v1beta1"
)

// KVCachePoolLister helps list KVCachePools.
// All objects returned here must be treated as read-only.
type KVCachePoolLister interface {
	// List lists all KVCachePools in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*resourcev1beta1.KVCachePool, err error)
	// Get retrieves the KVCachePool from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*resourcev1beta1.KVCachePool, error)
	KVCachePoolListerExpansion
}

// kVCachePoolLister implements the KVCachePoolLister interface.
type kVCachePoolLister struct {
	listers.ResourceIndexer[*resourcev1beta1.KVCachePool]
}

// NewKVCachePoolLister returns a new KVCachePoolLister.
func NewKVCachePoolLister(indexer cache.Indexer) KVCachePoolLister {
	return &kVCachePoolLister{listers.New[*resourcev1beta1.KVCachePool](indexer, resourcev1beta1.Resource("kvcachepool"))}
}
